name: Liquid Ajax Cart
url: https://liquid-ajax-cart.js.org
description: Ajaxifies Shopify cart sections and product forms like a boss

permalink: pretty

license:
  software: MIT License
  software_url: https://opensource.org/licenses/MIT

  docs: CC BY 3.0
  docs_url: https://creativecommons.org/licenses/by/3.0/

links_v2:
  docs:
    - title: Guides
      eyebrow: Guide
      subsections:
        - title: Setup
          links:
            - title: Installation
              file: installation
            - title: Cart section
              file: cart-section
            - title: Product forms
              file: product-forms
            - title: Cart totals in header
              file: cart-totals-in-header

        - title: Extension with JS
          links:
            - title: Lifecycle, events, API
              file: lifecycle-events-api
            - title: Ready snippets
              file: js-snippets

    - title: Versions
      subsections:
        - eyebrow: Versions
          links:
            - title: Releases v2.x.x
              file: releases
            - title: Differences from v1.x.x
              file: differences-from-v1

    - title: Reference
      subsections:
        - title: Core concepts
          eyebrow: Core concept
          links:
            - title: Request state
              file: request-state
            - title: Queue of requests
              file: queue-of-requests

        - title: Custom tags
          eyebrow: Custom tag
          links:
            - title: <ajax-cart-product-form>
              file: ajax-cart-product-form
            - title: <ajax-cart-quantity>
              file: ajax-cart-quantity

        - title: Data attributes
          eyebrow: Data attribute
          links:
            - title: data-ajax-cart-bind
              file: data-ajax-cart-bind
            - title: data-ajax-cart-errors
              file: data-ajax-cart-errors
            - title: data-ajax-cart-initial-state
              file: data-ajax-cart-initial-state
            - title: data-ajax-cart-quantity-input
              file: data-ajax-cart-quantity-input
            - title: data-ajax-cart-quantity-minus
              file: data-ajax-cart-quantity-minus
            - title: data-ajax-cart-quantity-plus
              file: data-ajax-cart-quantity-plus
            - title: data-ajax-cart-request-button
              file: data-ajax-cart-request-button
            - title: data-ajax-cart-section
              file: data-ajax-cart-section
            - title: data-ajax-cart-section-scroll
              file: data-ajax-cart-section-scroll
            - title: data-ajax-cart-static-element
              file: data-ajax-cart-static-element
            - title: data-ajax-cart-property-input
              file: data-ajax-cart-property-input

        - title: CSS classes
          eyebrow: CSS class
          links:
            - title: js-ajax-cart-init
              file: js-ajax-cart-init
            - title: js-ajax-cart-empty
              file: js-ajax-cart-empty
            - title: js-ajax-cart-not-empty
              file: js-ajax-cart-not-empty
            - title: js-ajax-cart-processing
              file: js-ajax-cart-processing

        - title: Events
          eyebrow: Event
          links:
            - title: liquid-ajax-cart:init
              file: event-init
            - title: liquid-ajax-cart:queue-start
              file: event-queue-start
            - title: liquid-ajax-cart:queue-end
              file: event-queue-end
            - title: liquid-ajax-cart:request-start
              file: event-request-start
            - title: liquid-ajax-cart:request-end
              file: event-request-end

        - title: JavaScript API
          links:
            - title: liquidAjaxCart {}
              file: liquid-ajax-cart
            - title: get()
              file: liquid-ajax-cart-get
            - title: add()
              file: liquid-ajax-cart-add
            - title: change()
              file: liquid-ajax-cart-change
            - title: update()
              file: liquid-ajax-cart-update
            - title: clear()
              file: liquid-ajax-cart-clear
            - title: init
              file: liquid-ajax-cart-init
            - title: cart
              file: liquid-ajax-cart-cart
            - title: processing
              file: liquid-ajax-cart-processing
            - title: conf()
              file: liquid-ajax-cart-conf

        - title: Configuration
          eyebrow: Configuration parameter
          id: configuration-subsection
          links:
            - title: requestErrorText
              file: request-error-text
            - title: binderFormatters
              file: binder-formatters
            - title: quantityTagAllowZero
              file: quantity-tag-allow-zero
            - title: quantityTagDebounce
              file: quantity-tag-debounce
            - title: updateOnWindowFocus
              file: update-on-window-focus

links:
  main:
    - title: Home
      url: /v1/
    - title: Guide
      url: /v1/guide/
    - title: JavaScript examples
      url: /v1/examples/
    - title: Reference
      url: /v1/reference/
    - title: Download
      url: /v1/releases/
  header:
    - title: Demo Store
      url: https://liquid-ajax-cart.myshopify.com/
    - title: GitHub
      url: https://github.com/EvgeniyMukhamedjanov/liquid-ajax-cart
  homepage:
    - title: View on GitHub
      icon: github
      brand: true
      url: https://github.com/EvgeniyMukhamedjanov/liquid-ajax-cart
  portfolio:
    - title: Deadly Ponies
      url: https://deadlyponies.com/
      image: deadlyponies.jpg
      meta: Made by <a href="https://www.almond.studio/" target="_blank">Studio Almond</a>
    - title: Naked Cashmere
      url: https://www.nakedcashmere.com/
      image: nakedcashmere.jpg
      meta: Made by <a href="https://avexdesigns.com/" target="_blank">Avex Designs</a>
    - title: BLUNT
      url: https://bluntumbrellas.com/
      image: bluntumbrellas.jpg
      meta: Made by <a href="https://www.almond.studio/" target="_blank">Studio Almond</a>
    - title: Alastin Skincare
      url: https://alastin.com/
      selector: .ltkpopup-close,.banner-close-button
      image: alastin.jpg
      meta: Integrated by <a href="https://avexdesigns.com/" target="_blank">Avex Designs</a>
    - title: RUBY
      url: https://rubynz.com/
      image: rubynz.jpg
      meta: Made by <a href="https://www.almond.studio/" target="_blank">Studio Almond</a>
    - title: NIGHTWORKS
      url: https://www.nightworksstudio.com/
      image: nightworksstudio.jpg
      meta: Made by <a href="https://www.almond.studio/" target="_blank">Studio Almond</a>
    - title: Middlehurst station
      url: https://middlehurst.co.nz/
      image: middlehurst.jpg
      meta: Made by <a href="https://github.com/subject-matter" target="_blank">Subject Matter</a>
    - title: Good Counsel
      url: https://goodcounsel.com/
      image: goodcounsel.jpg
      meta: Made by <a href="https://avexdesigns.com/" target="_blank">Avex Designs</a>
    - title: Lyttelton Lights
      url: https://lytteltonlights.com/
      selector: .klaviyo-close-form,.lyttelton-cookie .close_btn
      image: lytteltonlights.jpg
      meta: Integrated by <a href="https://github.com/subject-matter" target="_blank">Subject Matter</a>
    - title: Two islands
      url: https://twoislandsco.com/
      image: twoislands.jpg
      meta: Made by <a href="https://www.almond.studio/" target="_blank">Studio Almond</a>
    - title: Sadi studios
      url: https://sadi.love/
      selector: .upper-part-right
      image: sadi.jpg
      meta: Made by <a href="https://haroldao.com/" target="_blank">Harold AO</a>
    - title: Mahsa
      url: https://www.mahsa.co.nz/
      selector: .newsletter-popup__close
      image: mahsa.jpg
      meta: Made by <a href="https://www.almond.studio/" target="_blank">Studio Almond</a>
    - title: Kit and Ace
      url: https://www.kitandace.com/
      selector: .klaviyo-close-form
      image: kitandace.jpg
      meta: Made by <a href="https://avexdesigns.com/" target="_blank">Avex Designs</a>
    - title: Aleph Beauty
      url: https://alephbeauty.com/
      selector: .klaviyo-close-form
      image: alephbeauty.jpg
      meta: Made by <a href="https://www.almond.studio/" target="_blank">Studio Almond</a>
    - title: Brandon Blackwood
      url: https://brandonblackwood.com/
      selector: '.cookieconsent-wrapper .isense-close-icon,#closeIconContainer'
      image: brandonblackwood.jpg
      meta: Made by <a href="https://avexdesigns.com/" target="_blank">Avex Designs</a>
    - title: Pulse
      url: https://lovemypulse.com/
      selector: .klaviyo-close-form
      image: lovemypulse.jpg
      meta: Made by <a href="http://seanmythen.net/" target="_blank">Seán Mythen</a>
    - title: Talia di Napoli
      url: https://www.taliadinapoli.com/
      selector: .ot-cookie
      image: talia.jpg
      meta: Integrated by <a href="https://avexdesigns.com/" target="_blank">Avex Designs</a>
    - title: Natz
      url: https://www.drinknatz.com/
      selector: .age-verification__yes-button
      image: drinknatz.jpg
      meta: Made by <a href="https://haroldao.com/" target="_blank">Harold AO</a>
    - title: Starforge Systems
      url: https://starforgesystems.com/
      selector: .cc-compliance .cc-allow
      image: starforge.jpg
      meta: Made by <a href="https://avexdesigns.com/" target="_blank">Avex Designs</a>
    - title: Becuming
      url: https://becuming.com/
      selector: .klaviyo-close-form
      image: becuming.jpg
      meta: Made by <a href="https://www.almond.studio/" target="_blank">Studio Almond</a>
    - title: Novus Shoes
      url: https://novushoes.com/
      selector: .klaviyo-close-form
      image: novus.jpg
      meta: Made by <a href="https://avexdesigns.com/" target="_blank">Avex Designs</a>
    - title: Bks Shoes
      url: https://bksshoes.com/
      selector: .hulk_cookie_bar .bar_btn,.klaviyo-close-form
      image: bks.jpg
      meta: Made by <a href="https://avexdesigns.com/" target="_blank">Avex Designs</a>
    - title: Christopher Esber
      url: https://christopheresber.com.au/
      image: ce.jpg
      meta: Made by <a href="https://www.almond.studio/" target="_blank">Studio Almond</a>
    - title: La Favorita Shoes
      url: https://lafavorita.com/
      selector: .hulk_cookie_bar .bar_btn
      image: lafavorita.jpg
      meta: Made by <a href="https://avexdesigns.com/" target="_blank">Avex Designs</a>
    - title: Emma Lewisham
      url: https://emmalewisham.com/
      selector: .newsletter-popup__close
      image: emmalewisham.jpg
      meta: Made by <a href="https://www.almond.studio/" target="_blank">Studio Almond</a>
    - title: Eigenhain
      url: https://eigenhain.com/
      selector: '#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll'
      image: eigenhain.jpg
      meta: Made by <a href="https://haroldao.com/" target="_blank">Harold AO</a>
    - title: Sea to Summit
      url: https://seatosummit.com/
      selector: .popup-modal__toggle
      image: seatosummit.jpg
      meta: Made by <a href="https://avexdesigns.com/" target="_blank">Avex Designs</a>

  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/EvgeniyMukhamedjanov/liquid-ajax-cart
    - title: Contact form
      url: https://github.com/EvgeniyMukhamedjanov/liquid-ajax-cart/discussions/new
  reference:
    - title: Ajaxified sections
      file: sections
      description: Liquid Ajax Cart updates the HTML of your cart sections when the cart is changed
      links:
        - file: data-ajax-cart-section
          description: Defines an HTML container that will be re-rendered each time when the cart is changed.
        - file: data-ajax-cart-static-element
          description: Makes sure that an HTML element will not be replaced with new HTML even if it is within a `data-ajax-cart-section` container.
        - file: data-ajax-cart-section-scroll
          description: Makes sure that the scroll position of a scrollable area within a `data-ajax-cart-section` container will not be reset to top when HTML is updated.
        - title: subscribeToCartSectionsUpdate()
          file: subscribeToCartSectionsUpdate
          description: Registers your callbacks to be called after sections HTML is updated.
    - title: Product Forms
      file: product-forms
      description: Liquid Ajax Cart ajaxifies product forms once it is loaded.
      links:
        - title: .js-ajax-cart-form-in-progress
          file: js-ajax-cart-form-in-progress
          description: The CSS class gets attached to a product form when it is in process of adding a product to the cart.
    - title: Controls
      file: controls
      links: 
        - file: data-ajax-cart-request-button
          description: Performs a Cart Ajax API request when a link with the `routes.cart_*_url` or an element with the `data-ajax-cart-request-button` attribute is clicked.
        - file: data-ajax-cart-toggle-class-button
          description: Adds/removes a CSS class of the `body` tag on a user's click.
        - file: data-ajax-cart-quantity-input
          description: Ajaxifies an input field for a cart item's quantity.
        - file: data-ajax-cart-property-input
          description: Ajaxifies an input field for a cart item's property, a cart attribute or the cart note.
    - title: Messages
      file: data-ajax-cart-messages
      links:
        - file: data-ajax-cart-messages
          description: Shows error messages for product forms and cart items.
    - title: Body CSS classes
      file: body-css-classes
      links: 
        - title: .js-ajax-cart-set
          file: js-ajax-cart-set
          description: Is added if Liquid Ajax Cart has been loaded and got information about the user’s cart state.
        - title: .js-ajax-cart-empty
          file: js-ajax-cart-empty
          description: Is added if the cart is empty.
        - title: .js-ajax-cart-not-empty
          file: js-ajax-cart-not-empty
          description: Is added if the cart is not empty.
        - title: .js-ajax-cart-request-in-progress
          file: js-ajax-cart-request-in-progress
          description: Is added if there are one or more Cart Ajax API requests in progress.
        - title: .js-ajax-cart-not-compatible 
          file: js-ajax-cart-not-compatible
          description: Is added if a user's browser doesn't support all needed features.
    - title: State
      file: state
      description: A Javascript object that keeps the cart and app state.
      links:
        - file: data-ajax-cart-initial-state
          description: Defines initial cart state from `{{ cart | json }}`.
        - file: data-ajax-cart-bind-state
          description: Renders a cart state property anywhere on a page.
        - title: getCartState()
          file: getCartState
          description: Returns the cart state.
        - title: subscribeToCartStateUpdate()
          file: subscribeToCartStateUpdate
          description: Registers your callback to be called when the cart state is updated.
    - title: Cart Ajax API requests
      file: requests
      links: 
        - title: cartRequestGet()
          file: cartRequestGet
          description: Performs `GET /cart.js` request.
        - title: cartRequestUpdate()
          file: cartRequestUpdate
          description: Performs `POST /cart/update.js` request.
        - title: cartRequestAdd()
          file: cartRequestAdd
          description: Performs `POST /cart/add.js` request.
        - title: cartRequestChange()
          file: cartRequestChange
          description: Performs `POST /cart/change.js` request.
        - title: cartRequestClear()
          file: cartRequestClear
          description: Performs `POST /cart/clear.js` request.
        - title: subscribeToCartAjaxRequests()
          file: subscribeToCartAjaxRequests
          description: Registers your callbacks to be called before and after each Cart Ajax API request.
        - title: Request state
          file: requestState
          description: A Javascript object with information about each Cart Ajax API request.
        - title: Queues
          file: queues
          description: Shopfy Cart API requests don't get performed immediately but get added to queues.
    - title: Configuration
      file: configure
      description: Lets you set configuration parameters using the `configureCart` function and the `data-ajax-cart-configuration` attribute
      links:
        - file: productFormsFilter
          description: Sets which product forms shouldn't be ajaxified.
        - file: messageBuilder
          description: Sets HTML layout and the logic for `data-ajax-cart-messages` messages.
        - file: stateBinderFormatters
          description: Defines custom formatters for the `data-ajax-cart-bind-state` attribute.
        - file: addToCartCssClass
          description: Adds a CSS class to the `body` tag after successful adding a product to the cart.
        - file: updateOnWindowFocus
          description: Toggles the functionality that updates cart sections and the State when the `window` loses the focus and gets the focus again.
        - file: requestErrorText
          description: Defines the message text for the error when a Cart Ajax API request is not successful and doesn't have any error descriptions, or if the request is not performed.


ui:
  mode: 'light'
  brand:
    dark: "#5e8e3e"
    light: "#5e8e3e"
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    trianglify: true
    dark:
      color1: "#5e8e3e"
      color2: "#95bf47"
    light:
      color1: "#5e8e3e"
      color2: "#95bf47"
  masthead:
    color:
      dark: "#fff"
      light: "#fff"
    align:
      homepage: 'center'
      page: 'left'

social: false
#   github:
#     user: EvgeniyMukhamedjanov
#     repo: liquid-ajax-cart
#   twitter:
#     enabled: false
#     via:
#     hash:
#    account:
#  facebook:
#    enabled: false
#    profileUrl:

disqus: false

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-docs-theme.gemspec
  - LICENSE.md
  - README.md
  - screenshot.png
